### ISSUE TITLE
Table creation failed with mysql

### ISSUE THREAD

**Issue by patrickhusi** [dcramer/django-static-compiler#11]
With mysql it's not possible to run "migrate static_precompiler"

Error message:

<pre>
Running migrations for static_precompiler:
 - Migrating forwards to 0001_initial.
 > static_precompiler:0001_initial
FATAL ERROR - The following SQL query failed: ALTER TABLE `static_precompiler_dependency` ADD CONSTRAINT `static_precompiler_dependency_source_46b84c536e24ac66_uniq` UNIQUE (`source`, `depends_on`)
The error was: (1071, 'Specified key was too long; max key length is 767 bytes')
 ! Error found during real run of migration! Aborting.

 ! Since you have a database that does not support running
 ! schema-altering statements in transactions, we have had 
 ! to leave it in an interim state between migrations.

! You *might* be able to recover with:   - no dry run output for delete_unique_column() due to dynamic DDL, sorry
   = DROP TABLE `static_precompiler_dependency` CASCADE; []

 ! The South developers regret this has happened, and would
 ! like to gently persuade you to consider a slightly
 ! easier-to-deal-with DBMS (one that supports DDL transactions)
 ! NOTE: The error which caused the migration to fail is further up.
Error in migration: static_precompiler:0001_initial
DatabaseError: (1071, 'Specified key was too long; max key length is 767 bytes')
</pre>

**Comment by dcramer** [comment]
This is not the project you are looking for
